# Generated by Django 4.1.4 on 2023-02-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('god', '0002_book_delete_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_created',
            field=models.DateField(auto_created=True, default=0.0005392531344088437),
            preserve_default=False,
        ),
    ]
