# Generated by Django 4.1.4 on 2023-02-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('god', '0003_book_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date_created',
        ),
    ]
